volumes:
  mongo-data:
    external: true

services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  accounts:
    build:
      context: accounts
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./accounts:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo
      DATABASE_NAME: mongo
      WAIT_HOSTS: mongo:27017
      SIGNING_KEY: randomkey

  favorites:
    build:
      context: favorites
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./favorites:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo
      DATABASE_NAME: mongo
      WAIT_HOSTS: mongo:27017

  watchlists:
    build:
      context: watchlists
      dockerfile: Dockerfile.dev
    ports:
      - "8070:8000"
    volumes:
      - ./watchlists:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo/watchlists
      MONGOHOST: mongo
      DATABASE: watchlists
      MONGOUSER: root
      MONGOPASSWORD: pass
      SIGNING_KEY: randomkey
      # WAIT_HOSTS: mongo:27017

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
    restart: always

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_SAMPLE_SERVICE: http://localhost:8000
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_ACCOUNTS: http://localhost:8080
      REACT_APP_WATCHLISTS: http://localhost:8070
      # REACT_APP_FAVORITES: http://localhost:8090
