volumes:
  mongo-data:
    external: true

services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  user_accounts:
    build:
      context: user_accounts
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./user_accounts:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo
      DATABASE_NAME: mongo
      WAIT_HOSTS: mongo:27017
      # MONGO_USER: root
      # MONGO_PASSWORD: pass
      # MONGO_HOST: mongo
      # MONGO_DATABASE: accounts

  user_favorites:
    build:
      context: user_favorites
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./user_favorites:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo
      DATABASE_NAME: mongo
      WAIT_HOSTS: mongo:27017
      # MONGO_USER: root
      # MONGO_PASSWORD: pass
      # MONGO_HOST: mongo
      # MONGO_DATABASE: favorites

  user_watchlist:
    build:
      context: user_watchlist
      dockerfile: Dockerfile.dev
    ports:
      - "8070:8000"
    volumes:
      - ./user_watchlist:/app
    environment:
      DATABASE_URL: mongodb://root:pass@mongo
      DATABASE_NAME: mongo
      WAIT_HOSTS: mongo:27017
      # MONGO_USER: root
      # MONGO_PASSWORD: pass
      # MONGO_HOST: mongo
      # MONGO_DATABASE: watchlist

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
    restart: always

  # sample_service:
  #   build:
  #     context: ./sample_service
  #     dockerfile: ./Dockerfile.dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./sample_service:/app
  #   environment:
  #     DATABASE_URL: mongodb://root:pass@mongo
  #     DATABASE_NAME: mongo
  #     WAIT_HOSTS: mongo:27017

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_SAMPLE_SERVICE: http://localhost:8000
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_ACCOUNTS: http://localhost:8080
      # REACT_APP_WATCHLIST: http://localhost:8070
      # REACT_APP_FAVORITES: http://localhost:8090
