volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: anime@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_DISABLE_POSTFIX: 1

  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts, favorites, watchlists
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    ports:
      - 15432:5432

  accounts:
    build:
      context: ./accounts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./accounts:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS:
        postgres:5432
        # SIGNING_KEY:${SIGNING_KEY}

  favorites:
    build:
      context: ./favorites
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./favorites:/app
    environment:
      DATABASE_URL: postgresql://favorites:password@postgres/favorites
      WAIT_HOSTS: 
        postgres:5432
        # SIGNING_KEY:${SIGNING_KEY}

  watchlists:
    build:
      context: ./watchlists
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./watchlists:/app
    environment:
      DATABASE_URL: postgresql://watchlists:password@postgres/watchlists
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNTS_API_HOST: http://localhost:8000
      REACT_APP_FAVORITES_API_HOST: http://localhost:8090
      REACT_APP_WATCHLISTS_API_HOST: http://localhost:8080
